# -*- coding: utf-8 -*-
"""Minor Exam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oslR09pvnjoDRFARGlF79nKJYCjiO1AH
"""

!pip install -q wandb datasets huggingface_hub scikit-learn torchvision

import wandb
from huggingface_hub import login

wandb.login(key="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")
login(token="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")

import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else "NO GPU")

HF_USERNAME = "101bytespeedkunal"
HF_REPO_NAME = "cifar10-resnet18-exam"
GITHUB_REPO = "https://github.com/Givhel/MLOps_KunalMishra_M25CSA036"

device = "cuda" if torch.cuda.is_available() else "cpu"

from datasets import load_dataset

dataset = load_dataset("cifar10")

from torchvision import transforms
from torch.utils.data import DataLoader

transform_train = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))
])

transform_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))
])

def apply_transform(example, train=True):
    example["pixel_values"] = transform_train(example["img"]) if train else transform_test(example["img"])
    example["labels"] = example["label"]
    return example

dataset["train"] = dataset["train"].map(lambda x: apply_transform(x, True))
dataset["test"] = dataset["test"].map(lambda x: apply_transform(x, False))

dataset["train"].set_format("torch", ["pixel_values", "labels"])
dataset["test"].set_format("torch", ["pixel_values", "labels"])

train_loader = DataLoader(dataset["train"], batch_size=128, shuffle=True)
test_loader = DataLoader(dataset["test"], batch_size=128)

import torchvision.models as models
import torch.nn as nn

model = models.resnet18(pretrained=True)
model.fc = nn.Linear(model.fc.in_features, 10)
model.to(device)

wandb.init(
    project="minor-exam-cifar10",
    config={"epochs": 2, "batch_size": 128}
)

best_acc = 0

for epoch in range(2):   # 👈 ONLY 1 EPOCH
    model.train()
    correct, total, train_loss = 0, 0, 0

    for batch in train_loader:
        x = batch["pixel_values"].to(device)
        y = batch["labels"].to(device)

        optimizer.zero_grad()
        out = model(x)
        loss = criterion(out, y)
        loss.backward()
        optimizer.step()

        train_loss += loss.item()
        correct += (out.argmax(1) == y).sum().item()
        total += y.size(0)

    train_acc = correct / total

    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for batch in test_loader:
            x = batch["pixel_values"].to(device)
            y = batch["labels"].to(device)
            out = model(x)
            correct += (out.argmax(1) == y).sum().item()
            total += y.size(0)

    val_acc = correct / total

    wandb.log({
        "epoch": epoch,
        "train_loss": train_loss,
        "train_acc": train_acc,
        "val_acc": val_acc
    })

    torch.save(model.state_dict(), "best_model.pt")

best_acc = 0

for epoch in range(2):
    model.train()
    train_loss, correct, total = 0, 0, 0

    for batch in train_loader:
        x = batch["pixel_values"].to(device)
        y = batch["labels"].to(device)

        optimizer.zero_grad()
        out = model(x)
        loss = criterion(out, y)
        loss.backward()
        optimizer.step()

        train_loss += loss.item()
        correct += (out.argmax(1) == y).sum().item()
        total += y.size(0)

    train_acc = correct / total

    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for batch in test_loader:
            x = batch["pixel_values"].to(device)
            y = batch["labels"].to(device)
            out = model(x)
            correct += (out.argmax(1) == y).sum().item()
            total += y.size(0)

    val_acc = correct / total

    wandb.log({
        "epoch": epoch,
        "train_loss": train_loss,
        "train_acc": train_acc,
        "val_acc": val_acc
    })

    if val_acc > best_acc:
        best_acc = val_acc
        torch.save(model.state_dict(), "best_model.pt")

import torch
import torch.nn as nn
import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-3)

print("✅ Optimizer and loss defined")

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.models as models

device = "cuda" if torch.cuda.is_available() else "cpu"

model = models.resnet18(pretrained=True)
model.fc = nn.Linear(model.fc.in_features, 10)
model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-3)

print("✅ Model, optimizer, and loss initialized")

import wandb

wandb.init(
    project="minor-exam-cifar10",
    config={
        "epochs": 2,
        "batch_size": 128,
        "model": "resnet18"
    }
)

print("✅ wandb initialized")

best_acc = 0

for epoch in range(2):
    model.train()
    train_loss, correct, total = 0, 0, 0

    for batch in train_loader:
        x = batch["pixel_values"].to(device)
        y = batch["labels"].to(device)

        optimizer.zero_grad()
        out = model(x)
        loss = criterion(out, y)
        loss.backward()
        optimizer.step()

        train_loss += loss.item()
        correct += (out.argmax(1) == y).sum().item()
        total += y.size(0)

    train_acc = correct / total

    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for batch in test_loader:
            x = batch["pixel_values"].to(device)
            y = batch["labels"].to(device)
            out = model(x)
            correct += (out.argmax(1) == y).sum().item()
            total += y.size(0)

    val_acc = correct / total

    wandb.log({
        "epoch": epoch,
        "train_loss": train_loss,
        "train_acc": train_acc,
        "val_acc": val_acc
    })

    if val_acc > best_acc:
        best_acc = val_acc
        torch.save(model.state_dict(), "best_model.pt")

from huggingface_hub import HfApi

api = HfApi()
repo_id = f"{HF_USERNAME}/{HF_REPO_NAME}"

api.create_repo(repo_id=repo_id, exist_ok=True)
api.upload_file(
    path_or_fileobj="best_model.pt",
    path_in_repo="pytorch_model.bin",
    repo_id=repo_id
)

print("Model pushed to Hugging Face")

from huggingface_hub import hf_hub_download

model = models.resnet18()
model.fc = nn.Linear(model.fc.in_features, 10)

model_path = hf_hub_download(repo_id=repo_id, filename="pytorch_model.bin")
model.load_state_dict(torch.load(model_path))
model.to(device)
model.eval()

from sklearn.metrics import confusion_matrix
import numpy as np

y_true, y_pred = [], []

with torch.no_grad():
    for batch in test_loader:
        out = model(batch["pixel_values"].to(device))
        y_pred.extend(out.argmax(1).cpu().numpy())
        y_true.extend(batch["labels"].numpy())

class_names = dataset["train"].features["label"].names

wandb.log({
    "confusion_matrix": wandb.plot.confusion_matrix(
        y_true=y_true,
        preds=y_pred,
        class_names=class_names
    )
})

class_acc = {}

for i, name in enumerate(class_names):
    idx = np.where(np.array(y_true) == i)
    class_acc[name] = (np.array(y_pred)[idx] == i).mean()

for k, v in class_acc.items():
    print(f"{k}: {v}")